import org.joda.time.LocalDate;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        System.out.println(LocalDate.now().toString("dd/MM/yyyy"));
    }
}
